#!/usr/bin/env python3
"""
Report Assembler for GitHub Actions CI.

This script collects available project outputs (metrics, artifacts, logs) and 
generates a report.md file. It gracefully handles missing data and always exits 
with code 0 to prevent CI failures.

Usage:
    python assemble_report.py
"""

import os
import json
from pathlib import Path
from collections import defaultdict


def find_mlflow_runs():
    """Scan mlruns directory for available experiments and runs."""
    runs_info = []
    mlruns_path = Path("mlruns")
    
    if not mlruns_path.exists():
        return runs_info
    
    try:
        for exp_dir in mlruns_path.iterdir():
            if not exp_dir.is_dir() or exp_dir.name == "models":
                continue
            
            for run_dir in exp_dir.iterdir():
                if not run_dir.is_dir():
                    continue
                
                run_info = {"run_id": run_dir.name}
                
                # Check for metrics
                metrics_dir = run_dir / "metrics"
                if metrics_dir.exists():
                    metrics = {}
                    for metric_file in metrics_dir.iterdir():
                        try:
                            with open(metric_file, 'r') as f:
                                metrics[metric_file.name] = f.read().strip()
                        except (IOError, OSError):
                            pass
                    if metrics:
                        run_info["metrics"] = metrics
                
                # Check for params
                params_dir = run_dir / "params"
                if params_dir.exists():
                    params = {}
                    for param_file in params_dir.iterdir():
                        try:
                            with open(param_file, 'r') as f:
                                params[param_file.name] = f.read().strip()
                        except (IOError, OSError):
                            pass
                    if params:
                        run_info["params"] = params
                
                # Check for model artifacts
                artifacts_dir = run_dir / "artifacts"
                if artifacts_dir.exists():
                    artifacts = []
                    for artifact in artifacts_dir.iterdir():
                        artifacts.append(artifact.name)
                    if artifacts:
                        run_info["artifacts"] = artifacts
                
                runs_info.append(run_info)
    except (OSError, PermissionError):
        pass
    
    return runs_info


def find_project_artifacts():
    """Scan for available artifacts in the project."""
    artifacts_info = {}
    artifacts_path = Path("artifacts")
    
    if artifacts_path.exists():
        try:
            for item in artifacts_path.iterdir():
                if item.is_file():
                    artifacts_info[item.name] = str(item.stat().st_size)
        except (OSError, PermissionError):
            pass
    
    return artifacts_info


def find_model_files():
    """Find trained model files."""
    model_files = []
    
    # Check main artifacts directory
    artifacts_path = Path("artifacts")
    if artifacts_path.exists() and (artifacts_path / "model_state.pth").exists():
        model_files.append("artifacts/model_state.pth")
    
    # Check mlruns for model files
    mlruns_path = Path("mlruns")
    if mlruns_path.exists():
        for root, dirs, files in os.walk(mlruns_path):
            for file in files:
                if file.endswith(".pth"):
                    model_files.append(os.path.join(root, file))
    
    return model_files


def generate_report(runs: list, artifacts: dict, models: list) -> str:
    """Generate markdown report from collected data."""
    report_lines = [
        "# Project Report",
        "",
        "## Overview",
        "This report was automatically generated by the CI/CD pipeline.",
        "",
    ]
    
    # Check if we have any data
    has_data = bool(runs) or bool(artifacts) or bool(models)
    
    if not has_data:
        report_lines.append("**No results available** - This may be the first run or artifacts have not been generated yet.")
        return "\n".join(report_lines)
    
    # MLflow Runs Section
    if runs:
        report_lines.append("## Experiment Runs")
        report_lines.append("")
        for i, run in enumerate(runs, 1):
            report_lines.append(f"### Run {i}: {run.get('run_id', 'Unknown')}")
            report_lines.append("")
            
            # Parameters
            if "params" in run:
                report_lines.append("**Parameters:**")
                report_lines.append("```")
                for param_name, param_value in run["params"].items():
                    report_lines.append(f"  {param_name}: {param_value}")
                report_lines.append("```")
                report_lines.append("")
            
            # Metrics
            if "metrics" in run:
                report_lines.append("**Metrics:**")
                report_lines.append("```")
                for metric_name, metric_value in run["metrics"].items():
                    report_lines.append(f"  {metric_name}: {metric_value}")
                report_lines.append("```")
                report_lines.append("")
            
            # Artifacts
            if "artifacts" in run:
                report_lines.append("**Artifacts:**")
                for artifact in run["artifacts"]:
                    report_lines.append(f"  - {artifact}")
                report_lines.append("")
    
    # Project Artifacts Section
    if artifacts:
        report_lines.append("## Project Artifacts")
        report_lines.append("")
        for artifact_name, size in artifacts.items():
            report_lines.append(f"- {artifact_name} ({size} bytes)")
        report_lines.append("")
    
    # Model Files Section
    if models:
        report_lines.append("## Model Files")
        report_lines.append("")
        for model_path in models:
            report_lines.append(f"- {model_path}")
        report_lines.append("")
    
    report_lines.append("---")
    report_lines.append("*Report generated by assemble_report.py*")
    
    return "\n".join(report_lines)


def main():
    """Main entry point - collect data and generate report."""
    try:
        # Collect data from various sources
        runs = find_mlflow_runs()
        artifacts = find_project_artifacts()
        models = find_model_files()
        
        # Generate report
        report_content = generate_report(runs, artifacts, models)
        
        # Write report file
        report_path = Path("report.md")
        with open(report_path, 'w') as f:
            f.write(report_content)
        
        # Print success message
        print("✓ Report assembler completed successfully")
        print(f"✓ Report written to: {report_path.absolute()}")
        
        # Summary
        if runs:
            print(f"✓ Found {len(runs)} experiment run(s)")
        if artifacts:
            print(f"✓ Found {len(artifacts)} artifact(s)")
        if models:
            print(f"✓ Found {len(models)} model file(s)")
        if not (runs or artifacts or models):
            print("⊙ No data collected (report contains default message)")
        
        return 0
    
    except Exception as e:
        # Always exit cleanly even if something goes wrong
        print(f"⚠ Warning: {type(e).__name__}: {str(e)}")
        print("✓ Report assembler completed (with warnings)")
        
        # Create a minimal report
        try:
            report_content = "# Project Report\n\nNo results available.\n"
            with open("report.md", 'w') as f:
                f.write(report_content)
        except (IOError, OSError):
            pass
        
        return 0


if __name__ == "__main__":
    exit(main())
